services:
  - type: web
    name: real-time-news-sentiment-analyser
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: NEWSAPI_KEY
        sync: false
      - key: FLASK_DEBUG
        value: "false"
